export const icons = {
  google: '<Google />',
  twitter: '<Twitter />',
  arrow: '<Arrow />',
  home: '<Home />',
  selectedHome: '<SelectedHome />',
  explore: '<Explore />',
  selectedExplore: ' <SelectedExplore />',
  notifications: '<Notifications />',
  selectedNotifications: '<SelectedNotifications />',
  messages: '<Messages />',
  selectedMessages: '<SelectedMessages />',
  bookmarks: '<Bookmarks />',
  selectedBookmarks: '<SelectedBookmarks />',
  lists: '<Lists />',
  selectedLists: '<SelectedLists />',
  profile: '<Profile />',
  selectedProfile: '<SelectedProfile />',
  more: '<More />',
  search: '<Search />',
  logout: '<LogOut />',
  image: ' <Image />',
  burger: '<Burger />',
};
